name: GitHub Skyline

on:
  schedule:
    - cron:  '0 */8 * * *'
  workflow_dispatch: #run manually

jobs:
  skyline:
#    runs-on: ubuntu-latest
    steps:
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.skyline.svg
        base: ""
        plugin_skyline: yes
        plugin_skyline_year: 2022
        plugin_skyline_frames: 60
        plugin_skyline_quality: 1